src/Entity/Energie.php
<?php

namespace App\Entity;

use App\Repository\EnergieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EnergieRepository::class)
 */
class Energie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_energie;

    /**
     * @ORM\OneToMany(targetEntity=Automobile::class, mappedBy="energie")
     */
    private $automobiles;

    public function __construct()
    {
        $this->automobiles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEnergie(): ?string
    {
        return $this->nom_energie;
    }

    public function setNomEnergie(string $nom_energie): self
    {
        $this->nom_energie = $nom_energie;

        return $this;
    }

    /**
     * @return Collection|Automobile[]
     */
    public function getAutomobiles(): Collection
    {
        return $this->automobiles;
    }

    public function addAutomobile(Automobile $automobile): self
    {
        if (!$this->automobiles->contains($automobile)) {
            $this->automobiles[] = $automobile;
            $automobile->setEnergie($this);
        }

        return $this;
    }

    public function removeAutomobile(Automobile $automobile): self
    {
        if ($this->automobiles->removeElement($automobile)) {
            // set the owning side to null (unless already changed)
            if ($automobile->getEnergie() === $this) {
                $automobile->setEnergie(null);
            }
        }

        return $this;
    }

    public function __toString()
  {
    return $this->getNomEnergie();
  }
}

src/Form/EnergieType.php
<?php

namespace App\Form;

use App\Entity\Energie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnergieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_energie')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Energie::class,
        ]);
    }
}

src/Controller/EnergieController.php
<?php

namespace App\Controller;

use App\Entity\Energie;
use App\Form\EnergieType;
use App\Repository\EnergieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/energie")
 */
class EnergieController extends AbstractController
{
    /**
     * @Route("/", name="energie_index", methods={"GET"})
     */
    public function index(EnergieRepository $energieRepository): Response
    {
        $user = $this->getUser();
        $role = $user->getRoles();
        if($role[0]==='ROLE_USER'){
            return $this->render('energie/index.html.twig', [
                'energies' => $energieRepository->findAll(),
            ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/new", name="energie_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = $this->getUser();
        $role = $user->getRoles();
        if($role[0]==='ROLE_USER'){
            $energie = new Energie();
        $form = $this->createForm(EnergieType::class, $energie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($energie);
            $entityManager->flush();

            return $this->redirectToRoute('energie_index');
        }

        return $this->render('energie/new.html.twig', [
            'energie' => $energie,
            'form' => $form->createView(),
        ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/{id}", name="energie_show", methods={"GET"})
     */
    public function show(Energie $energie): Response
    {
        $user = $this->getUser();
        $role = $user->getRoles();
        if($role[0]==='ROLE_USER'){
            return $this->render('energie/show.html.twig', [
                'energie' => $energie,
            ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/{id}/edit", name="energie_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Energie $energie): Response
    {
        $user = $this->getUser();
        $role = $user->getRoles();
        if($role[0]==='ROLE_USER'){
            $form = $this->createForm(EnergieType::class, $energie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('energie_index');
        }

        return $this->render('energie/edit.html.twig', [
            'energie' => $energie,
            'form' => $form->createView(),
        ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/{id}", name="energie_delete", methods={"POST"})
     */
    public function delete(Request $request, Energie $energie): Response
    {
        $user = $this->getUser();
        $role = $user->getRoles();
        if($role[0]==='ROLE_USER'){
            // if the energie is connected to an automobile it will not be deleted or cause an exception
        if ($this->isCsrfTokenValid('show'.$energie->getId(), $request->request->get('_token'))){
            return $this->render('energie/show.html.twig', [
                'energie' => $energie,
            ]);
        }
        if ($this->isCsrfTokenValid('delete'.$energie->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($energie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('energie_index');
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }
}

templates/energie/_delete_form.html.twig
{% block body %}
{% if energie.automobiles|length > 0 %}
<form method="post" action="{{ path('energie_show', {'id': energie.id}) }}" onsubmit="return alert('you can not delete this item. this item is connected to other automobile !!!');">
    <input type="hidden" name="_token" value="{{ csrf_token('show' ~ energie.id) }}">
    <button class="btn">Delete</button>
</form>
{% else %}
<form method="post" action="{{ path('energie_delete', {'id': energie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ energie.id) }}">
    <button class="btn">Delete</button>
</form>
{% endif %}
{% endblock %}

templates/energie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Energie{% endblock %}

{% block body %}
    <h1>Edit Energie</h1>

    {{ include('energie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('energie_index') }}">back to list</a>

    {{ include('energie/_delete_form.html.twig') }}
{% endblock %}

templates/energie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Energie index{% endblock %}

{% block body %}
    <h1>Energie index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Energie</th>
                <th>Automobile</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for energie in energies %}
            <tr>
                <td>{{ energie.id }}</td>
                <td>{{ energie.nomEnergie }}</td>
                <td>
                <ul>
                {% for Automobile in energie.automobiles %}
                <li>{{ Automobile.getNImmatriculation() }}</li>
                {% endfor %}
                </ul>
                </td>
                <td>
                    <a href="{{ path('energie_show', {'id': energie.id}) }}">show</a>
                    <a href="{{ path('energie_edit', {'id': energie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('energie_new') }}">Create new</a>
{% endblock %}

templates/energie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Energie{% endblock %}

{% block body %}
    <h1>Create new Energie</h1>

    {{ include('energie/_form.html.twig') }}

    <a href="{{ path('energie_index') }}">back to list</a>
{% endblock %}

templates/energie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Energie{% endblock %}

{% block body %}
    <h1>Energie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ energie.id }}</td>
            </tr>
            <tr>
                <th>Energie</th>
                <td>{{ energie.nomEnergie }}</td>
            </tr>
            <tr>
                <th>Automobile</th>
                <td><ul>
                {% for Automobile in energie.automobiles %}
                <li>{{ Automobile.getNImmatriculation() }}</li>
                {% endfor %}
                </ul></td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('energie_index') }}">back to list</a>

    <a href="{{ path('energie_edit', {'id': energie.id}) }}">edit</a>

    {{ include('energie/_delete_form.html.twig') }}
{% endblock %}