src/Entity/ModeleYear.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Entity;
use App\Repository\ModeleYearRepository;
/**
 * @Entity
 */
class ModeleYear
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $modele_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $year_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getModeleId(): ?int
    {
        return $this->modele_id;
    }

    public function setModeleId(int $modele_id): self
    {
        $this->modele_id = $modele_id;

        return $this;
    }

    public function getYearId(): ?int
    {
        return $this->year_id;
    }

    public function setYearId(int $year_id): self
    {
        $this->year_id = $year_id;

        return $this;
    }
}

src/Form/ModeleYearType.php
<?php

namespace App\Form;

use App\Entity\ModeleYear;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ModeleYearType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('modele_id')
            ->add('year_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ModeleYear::class,
        ]);
    }
}

src/Controller/ModeleYearController.php
<?php

namespace App\Controller;

use App\Entity\ModeleYear;
use App\Form\ModeleYearType;
use App\Repository\ModeleYearRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/modele/year")
 */
class ModeleYearController extends AbstractController
{
    /**
     * @Route("/", name="modele_year_index", methods={"GET"})
     */
    public function index(ModeleYearRepository $modeleYearRepository): Response
    {
        $user = $this->getUser();
        if($user){
            return $this->render('modele_year/index.html.twig', [
                'modele_years' => $modeleYearRepository->findAll(),
            ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/new", name="modele_year_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = $this->getUser();
        if($user){
            $modeleYear = new ModeleYear();
        $form = $this->createForm(ModeleYearType::class, $modeleYear);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($modeleYear);
            $entityManager->flush();

            return $this->redirectToRoute('modele_year_index');
        }

        return $this->render('modele_year/new.html.twig', [
            'modele_year' => $modeleYear,
            'form' => $form->createView(),
        ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/{id}", name="modele_year_show", methods={"GET"})
     */
    public function show(ModeleYear $modeleYear): Response
    {
        $user = $this->getUser();
        if($user){
            return $this->render('modele_year/show.html.twig', [
                'modele_year' => $modeleYear,
            ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/{id}/edit", name="modele_year_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, ModeleYear $modeleYear): Response
    {
        $user = $this->getUser();
        if($user){
            $form = $this->createForm(ModeleYearType::class, $modeleYear);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('modele_year_index');
        }

        return $this->render('modele_year/edit.html.twig', [
            'modele_year' => $modeleYear,
            'form' => $form->createView(),
        ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/{id}", name="modele_year_delete", methods={"POST"})
     */
    public function delete(Request $request, ModeleYear $modeleYear): Response
    {
        $user = $this->getUser();
        if($user){
            if ($this->isCsrfTokenValid('delete'.$modeleYear->getId(), $request->request->get('_token'))) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->remove($modeleYear);
                $entityManager->flush();
            }
    
            return $this->redirectToRoute('modele_year_index');    
        }else{
            return $this->redirectToRoute('homepage');
        }
    }
}

templates/modele_year/_delete_form.html.twig
<form method="post" action="{{ path('modele_year_delete', {'id': modele_year.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ modele_year.id) }}">
    <button class="btn">Delete</button>
</form>

templates/modele_year/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ModeleYear{% endblock %}

{% block body %}
    <h1>Edit ModeleYear</h1>

    {{ include('modele_year/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('modele_year_index') }}">back to list</a>

    {{ include('modele_year/_delete_form.html.twig') }}
{% endblock %}

templates/modele_year/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ModeleYear index{% endblock %}

{% block body %}
    <h1>ModeleYear index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Modele_id</th>
                <th>Year_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for modele_year in modele_years %}
            <tr>
                <td>{{ modele_year.id }}</td>
                <td>{{ modele_year.modeleId }}</td>
                <td>{{ modele_year.yearId }}</td>
                <td>
                    <a href="{{ path('modele_year_show', {'id': modele_year.id}) }}">show</a>
                    <a href="{{ path('modele_year_edit', {'id': modele_year.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('modele_year_new') }}">Create new</a>
{% endblock %}

templates/modele_year/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ModeleYear{% endblock %}

{% block body %}
    <h1>Create new ModeleYear</h1>

    {{ include('modele_year/_form.html.twig') }}

    <a href="{{ path('modele_year_index') }}">back to list</a>
{% endblock %}

templates/modele_year/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ModeleYear{% endblock %}

{% block body %}
    <h1>ModeleYear</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ modele_year.id }}</td>
            </tr>
            <tr>
                <th>Modele_id</th>
                <td>{{ modele_year.modeleId }}</td>
            </tr>
            <tr>
                <th>Year_id</th>
                <td>{{ modele_year.yearId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('modele_year_index') }}">back to list</a>

    <a href="{{ path('modele_year_edit', {'id': modele_year.id}) }}">edit</a>

    {{ include('modele_year/_delete_form.html.twig') }}
{% endblock %}