src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 */
class Categorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_categorie;

    /**
     * @ORM\OneToMany(targetEntity=Automobile::class, mappedBy="categorie")
     */
    private $automobiles;

    /**
     * @ORM\OneToMany(targetEntity=Modele::class, mappedBy="categorie")
     */
    private $modeles;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function __construct()
    {
        $this->automobiles = new ArrayCollection();
        $this->modeles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nom_categorie;
    }

    public function setNomCategorie(string $nom_categorie): self
    {
        $this->nom_categorie = $nom_categorie;

        return $this;
    }

    /**
     * @return Collection|Automobile[]
     */
    public function getAutomobiles(): Collection
    {
        return $this->automobiles;
    }

    public function addAutomobile(Automobile $automobile): self
    {
        if (!$this->automobiles->contains($automobile)) {
            $this->automobiles[] = $automobile;
            $automobile->setCategorie($this);
        }

        return $this;
    }

    public function removeAutomobile(Automobile $automobile): self
    {
        if ($this->automobiles->removeElement($automobile)) {
            // set the owning side to null (unless already changed)
            if ($automobile->getCategorie() === $this) {
                $automobile->setCategorie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Modele[]
     */
    public function getModeles(): Collection
    {
        return $this->modeles;
    }

    public function addModele(Modele $modele): self
    {
        if (!$this->modeles->contains($modele)) {
            $this->modeles[] = $modele;
            $modele->setCategorie($this);
        }

        return $this;
    }

    public function removeModele(Modele $modele): self
    {
        if ($this->modeles->removeElement($modele)) {
            // set the owning side to null (unless already changed)
            if ($modele->getCategorie() === $this) {
                $modele->setCategorie(null);
            }
        }

        return $this;
    }

    public function __toString()
  {
    return $this->getNomCategorie();
  }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_categorie')
            ->add('image',FileType::class, [
                'label' => 'upload image',
                'required' => true,
                'data_class'=> null])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/categorie")
 */
class CategorieController extends AbstractController
{
    /**
     * @Route("/", name="categorie_index", methods={"GET"})
     */
    public function index(CategorieRepository $categorieRepository): Response
    {
        $user = $this->getUser();
        $role = $user->getRoles();
        if($role[0]==='ROLE_ADMIN'){
            return $this->render('categorie/index.html.twig', [
                'categories' => $categorieRepository->findAll(),
            ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/new", name="categorie_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = $this->getUser();
        $role = $user->getRoles();
        if($role[0]==='ROLE_ADMIN'){
            $categorie = new Categorie();
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //to upload the image
            $imageFile = $form->get('image')->getData();
            $fileName = md5(uniqid()).'.'.$imageFile->getExtension();
            $imageFile->move( $this->getParameter('image_directory'), $fileName);
            $categorie->setImage($fileName);
            $categorie = $form->getData();
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($categorie);
            $entityManager->flush();

            return $this->redirectToRoute('categorie_index');
        }

        return $this->render('categorie/new.html.twig', [
            'categorie' => $categorie,
            'form' => $form->createView(),
        ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/{id}", name="categorie_show", methods={"GET"})
     */
    public function show(Categorie $categorie): Response
    {
        $user = $this->getUser();
        $role = $user->getRoles();
        if($role[0]==='ROLE_ADMIN'){
            return $this->render('categorie/show.html.twig', [
                'categorie' => $categorie,
            ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/{id}/edit", name="categorie_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Categorie $categorie): Response
    {
        $user = $this->getUser();
        $role = $user->getRoles();
        if($role[0]==='ROLE_ADMIN'){
            $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('image')->getData();
            $fileName = md5(uniqid()).'.'.$imageFile->getExtension();
            $imageFile->move( $this->getParameter('image_directory'), $fileName);
            $categorie->setImage($fileName);
            $categorie = $form->getData();
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('categorie_index');
        }

        return $this->render('categorie/edit.html.twig', [
            'categorie' => $categorie,
            'form' => $form->createView(),
        ]);
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }

    /**
     * @Route("/{id}", name="categorie_delete", methods={"POST"})
     */
    public function delete(Request $request, Categorie $categorie): Response
    {
        $user = $this->getUser();
        $role = $user->getRoles();
        if($role[0]==='ROLE_ADMIN'){
            // if the categorie is connected to a modele, it will not be deleted or cause an exception
        if ($this->isCsrfTokenValid('show'.$categorie->getId(), $request->request->get('_token'))){
            return $this->render('categorie/show.html.twig', [
                'categorie' => $categorie,
            ]);
        }        
        if ($this->isCsrfTokenValid('delete'.$categorie->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($categorie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('categorie_index');
        }else{
            return $this->redirectToRoute('homepage');
        }
        
    }
}

templates/categorie/_delete_form.html.twig
{% block body %}
{% if categorie.modeles|length > 0 %}
<form method="post" action="{{ path('categorie_show', {'id': categorie.id}) }}" onsubmit="return alert('you can not delete this item. this item is connected to other models !!!');">
    <input type="hidden" name="_token" value="{{ csrf_token('show' ~ categorie.id) }}">
    <button class="btn">Delete</button>
</form>
{% else %}
<form method="post" action="{{ path('categorie_delete', {'id': categorie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ categorie.id) }}">
    <button class="btn">Delete</button>
</form>
{% endif %}
{% endblock %}

templates/categorie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Categorie{% endblock %}

{% block body %}
    <h1>Edit Categorie</h1>

    {{ include('categorie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('categorie_index') }}">back to list</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}

templates/categorie/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Categorie index{% endblock %}

{% block body %}
    <h1>Categorie index</h1>
            <section id="gallery">
            <div class="container">
            
                <div class="row">
                {% for categorie in categories %}
                    <div class="col-lg-4 mb-4">
                        <div class="card">
                            <img src="{{asset('uploads/')}}{{categorie.image}}" alt="" class="card-img-top">
                            <div class="card-body">
                                <h5 class="card-title">{{  categorie.nomCategorie }}</h5>
                                <p class="card-text"><ul>
                {% for modele in categorie.modeles %}
                <li>{{ modele.getNomModele() }}</li>
                {% endfor %}
                </ul></p>
                                <a href="{{ path('categorie_show', {'id': categorie.id}) }}"class="btn btn-outline-success btn-sm">show</a>
                    <a href="{{ path('categorie_edit', {'id': categorie.id}) }}"class="btn btn-outline-danger btn-sm">edit</a>
                </div>
                      </div>
                    </div>
                    {% else %}
                <h1>no records found<h1>

        {% endfor %}
                </div>

            </div>
            </section>
            <div class="text-center">
            <a href="{{ path('categorie_new') }}" type="button" class="btn btn-primary" >Create new</a>
            </div>

{% endblock %}

templates/categorie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Categorie{% endblock %}

{% block body %}
    <h1>Create new Categorie</h1>

    {{ include('categorie/_form.html.twig') }}

    <a href="{{ path('categorie_index') }}">back to list</a>
{% endblock %}

templates/categorie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categorie{% endblock %}

{% block body %}
    <h1>Categorie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ categorie.id }}</td>
            </tr>
            <tr>
                <th>Nom Categorie</th>
                <td>{{ categorie.nomCategorie }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td><img src="{{asset('uploads/')}}{{categorie.image}}" style="width:100px;height:100px" alt=""></td>
            </tr>
            <tr>
                <th>Modeles</th>
                <td>
                <ul>
                {% for modele in categorie.modeles %}
                <li>{{ modele.getNomModele() }}</li>
                {% endfor %}
                </ul>
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('categorie_index') }}">back to list</a>

    <a href="{{ path('categorie_edit', {'id': categorie.id}) }}">edit</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}
{% block javascripts %}
<script>
console.log(#categorie-id);
if ((categorie.modeles).lenght === 0) { 
    console.log("Array is empty!") ;
}else{
    console.log("Array is not empty!");
}
</script>
{% endblock %}